on:
  push:
    branches:
      - master
  pull_request:

name: R CMD check

jobs:
  check:
    name: R CMD check
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
    - uses: actions/checkout@v3

    - name: Set directories
      run: |
        echo "R_PKG_DIR=${R_HOME}/site-library" >> $GITHUB_ENV

    - name: Restore the package directory
      uses: actions/cache@v3
      with:
        path: ${{ env.R_PKG_DIR }}
        key: preinstalled-packages

    - name: Install packages
      shell: Rscript {0}
      run: |
        desc <- read.dcf("DESCRIPTION")
        deps <- desc[,intersect(colnames(desc), c("Depends", "Imports", "Suggests"))]
        deps <- sub("[ ,].*", "", unlist(strsplit(deps, "\n")))
        BiocManager::install(deps)

    - name: Build the package
      run: R CMD build .

    - name: Test the package
      run: |
        tarball=$(ls *.tar.gz)
        R CMD check --no-manual $tarball
